### ISSUE TITLE
Performance of Apart

### ISSUE THREAD

**Issue by vsht** [F-Feng/APart#2]
Recently there was a question on [Mathematica SE](https://mathematica.stackexchange.com/questions/147031/apart-expression-returns-unevaluated) regarding the built-in `Apart`. So I wanted to suggest the OP to use APart but it seems that APart requires ages to process the given expression

```
<< Apart`

exp = -((q qp^3 vq (I Abs[wn] + 
        qp v[-1]) (v[-1] - v[1])^2 (-I Abs[wn] + qp v[1]) (wn^2 + 
        q qp v[-1] v[1]) (-wn^2 + qp^2 v[-1] v[1]))/(2 \[Pi]^2 (q + 
        qp) (-q1 + 
        qp) \[Beta] (qp - (I wn)/v[-1]) (qp + (I wn)/
         v[-1]) v[-1]^2 (-I Abs[wn] + 
        q v[-1]) (2 vq v[-1] + \[Pi] v[-1]^2) (qp - (Sqrt[\[Pi]] wn)/
         Sqrt[-v[-1] (2 vq + \[Pi] v[-1])]) (qp + (Sqrt[\[Pi]] wn)/
         Sqrt[-v[-1] (2 vq + \[Pi] v[-1])]) (qp - (I wn)/
          v[1])^2 (qp + (I wn)/v[1])^2 v[1]^4 (I Abs[wn] + q v[1])))

ApartAll[exp, {qp}]

ApartAll2[exp_, vars_] := 
 Module[{tmp, VF}, 
  tmp = Distribute[VF[Expand[exp, Alternatives @@ vars]]];
  tmp = tmp /. VF[ex_] :> ApartAll[ex, vars];
  Return[tmp];]

res = ApartAll2[exp, {qp}]; // AbsoluteTiming

```

I gave up after waiting about 4 minutes on my ThinkPad T460p (i5-6440HQ and 32 GB RAM) with Mathematica 11.0.1. 

Usually APart is very fast on similar polynomials, so i'm curious if the current behavior is expected or there is still some room for improvements in the code to make things work faster.

Cheers,
Vladyslav

**Comment by F-Feng** [comment]
Hi, Vladyslav, sorry for missing this issue.

These is a function called **InnerCollectFunction** in APart package, and its default value is set to **Factor**, it is the main reason for such a long time, when I set **InnerCollectFunction** to **Identity**, the timing is around 40s.

![apart](https://user-images.githubusercontent.com/8832209/35308638-84f34948-00e3-11e8-904e-96ca27698df7.png)

**Comment by vsht** [comment]
Hi Feng,

thanks for you answer. The original question on Mathematica.SE is still unanswered, so I will now recommend APart there and a add a link to this thread.
